### ISSUE TITLE
Bug in exit code logic

### ISSUE THREAD

**Issue by inverse** [valayDave/tell-me-your-secrets#16]
Just noticed that there is a bug in the exit code logic.

- Returns 1 when no errors found with or without the `-e` flag

I can take a look when I have some time...

---
Doens't seem to affect master only on latest packaged

**Comment by inverse** [comment]
Was non-issue

**Comment by jeanCarloMachado** [comment]
Actually, it is happening to me :). What was the problem in your case?

**Comment by inverse** [comment]
@jeanCarloMachado what version of `tell-me-your-secrets` are you running and how are you invoking it?

**Comment by jeanCarloMachado** [comment]
Version: 2.4.0

For example:
```sh
tell-me-your-secrets -e . ; echo $?

2022-07-12 14:17:58,720 - Tell-Me-Your-Secrets - INFO - Secret Sniffer Initialised For Path: /Users/jean.machado/projects/local-ci
2022-07-12 14:18:00,257 - Tell-Me-Your-Secrets - INFO - Processed 131 files and found 0 matches from the search_path /Users/jean.machado/projects/local-ci in 1.54 seconds
(False, True)
1
```
Exited with failure although did not find issues.

**Comment by inverse** [comment]
Fixed in https://github.com/valayDave/tell-me-your-secrets/pull/56

**Comment by inverse** [comment]
Still need to release

**Comment by inverse** [comment]
@jeanCarloMachado Fixed in https://github.com/valayDave/tell-me-your-secrets/releases/tag/v2.4.1

Will be published upstream shortly
