### ISSUE TITLE
Add Codacy Badges to README

### ISSUE THREAD

**Issue by inverse** [valayDave/tell-me-your-secrets#47]
Unfortunately I cannot do it as I am not the repo owner, perhaps there is a way to add me as a collaborater on Codacy? 

Would be nice to have the badges as flare on the README :)

**Comment by valayDave** [comment]
Badges : 

[![Codacy Badge](https://app.codacy.com/project/badge/Grade/54d135292db445ec8eb988b57c747dc2)](https://www.codacy.com/gh/valayDave/tell-me-your-secrets/dashboard?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=valayDave/tell-me-your-secrets&amp;utm_campaign=Badge_Grade)

[![Codacy Badge](https://app.codacy.com/project/badge/Coverage/54d135292db445ec8eb988b57c747dc2)](https://www.codacy.com/gh/valayDave/tell-me-your-secrets/dashboard?utm_source=github.com&utm_medium=referral&utm_content=valayDave/tell-me-your-secrets&utm_campaign=Badge_Coverage)
