### ISSUE TITLE
Leverage Github for releases

### ISSUE THREAD

**Issue by inverse** [valayDave/tell-me-your-secrets#7]
It would be neat to leverage Github releases when releasing new code to be notified when new releases happen.

Could leverage Github Actions to automatically push to pipy too.

Happy to help out on this one.

**Comment by valayDave** [comment]
Hey. That Sounds Like a good idea. It would would be very nice if you could help.

**Comment by inverse** [comment]
Once we get #8 this would come next - It should be fairly straight forward to extend but will require you to add your credentials for pypi to the project's github secrets. I've never done it for Python packaging for Github Actions but it should be just a case of.

- You'll create the release via Github UI
- That'll create a git tag that'll trigger a new workflow
- This will run through the pypi upload :boom:

**Comment by inverse** [comment]
@valayDave started a PR that should suffice. One thing that would be neat to document is a `CHANGELOG` of the changes that have gone in. 

Some projects do thia via the releases section on github. Like:

- https://github.com/home-assistant/core/releases/tag/0.113.1

While others maintain a `CHANGELOG.md` file within the repo like

- https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md

**Comment by inverse** [comment]
@valayDave what do you think of the suggested CHANGELOG or github releases to capture changes in the lib?
